### ISSUE TITLE
Definir as funcionalidades da aplicação

### ISSUE THREAD

**Issue by caioosilva** [caioosilva/UpFitness-FrontProject#1]
definir funcionalidades do aplicativo

**Comment by caioosilva** [comment]
fazer wirdeframe da tela de login

**Comment by caioosilva** [comment]
criar o nome do aplicativo

**Comment by luisagnes** [comment]
tela das atleticas, irmão

**Comment by caioosilva** [comment]
implementar tela de inicio

**Comment by caioosilva** [comment]
implementar tela de perfil

**Comment by caioosilva** [comment]
implementar tela de cadastro

**Comment by caioosilva** [comment]
implementar tela de historico

**Comment by luisagnes** [comment]
telas de perfil, login, cadastro e home todas definidas
