### ISSUE TITLE
testar aplicação

### ISSUE THREAD

**Issue by caioosilva** [caioosilva/UpFitness-FrontProject#5]

**Comment by luisagnes** [comment]
aplicação com todas as telas funcionais

**Comment by caioosilva** [comment]
aplicação testada pelos 3 e terminada em call

**Comment by luisagnes** [comment]
a validação de login, como conversada em call, só existe por meio da utilização do Firebase ou algum dataBase

**Comment by isaiasZ** [comment]
a parte da tela de login possui um botão acima na tela home
